### ISSUE TITLE
Settings view seems to be missing values

### ISSUE THREAD

**Issue by kevinSuttle** [jamiewilson/predawn-ui#25]
![screen shot 2015-05-26 at 10 16 13 am](https://cloud.githubusercontent.com/assets/95672/7815834/70a154d8-0390-11e5-9f3c-058ce43fdd92.png)

**Comment by khornberg** [comment]
I'm getting this on Ubuntu as well.

**Comment by jake-wies** [comment]
Yes also seeing this as well as of July 8th
