### ISSUE TITLE
completion text color conflict

### ISSUE THREAD

**Issue by robmoggach** [jamiewilson/predawn-ui#29]
I have an issue when using predawn and predawn-syntax.

See the attached image... when you start to enter text the completion hides some of the letters.

![screenshot 2016-02-11 14 21 46](https://cloud.githubusercontent.com/assets/184759/12987689/371eb6c0-d0cb-11e5-8ed3-8aad6cdae571.jpg)

**Comment by robmoggach** [comment]
duplicate of [#28](https://github.com/jamiewilson/predawn-ui/issues/28)

**Comment by p1ch-jp** [comment]
https://github.com/jamiewilson/predawn-ui/pull/31
