### ISSUE TITLE
Fuzzy finder layout bug

### ISSUE THREAD

**Issue by andreiciceu** [jamiewilson/predawn-ui#39]
Hello,

There is a visual bug in displaying the Fuzzy Search pannel, in Atom. A + sign in a square appears above some of the file names, as you can see in the attached screenshot.

OS: Windows 10
Atom: 1.12.9
Predawn-ui: 1.0.2
Predawn-syntax: 1.0.4
![image](https://cloud.githubusercontent.com/assets/9255607/21781307/7f377fb2-d6b7-11e6-9fba-df5def28cdfb.png)

**Comment by jamiewilson** [comment]
Hey @p1ch-jp, wanna take a look at this if you get a chance?

**Comment by p1ch-jp** [comment]
@jamiewilson OK, I take a look at this.

**Comment by jamiewilson** [comment]
This looks great to me. Good work!

**Comment by p1ch-jp** [comment]
Thanks, I'll marge it.

**Comment by entr** [comment]
Guys, I still feel it can be improved. This is what I'm seeing in Atom 14.1 and predawn-ui 1.0.6

![Imgur](http://i.imgur.com/a63ND6r.png)

Highlighted parts in finder results are hard to read. You agree?
